CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260411105454_InitialCreate') THEN
    CREATE TABLE "Members" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(256) NOT NULL,
        "MobileNo" character varying(32) NOT NULL,
        "Address" character varying(512) NOT NULL,
        "IsActive" boolean NOT NULL,
        "IsRegistrationFormSubmitted" boolean NOT NULL,
        "Designation" character varying(256) NOT NULL,
        CONSTRAINT "PK_Members" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260411105454_InitialCreate') THEN
    CREATE TABLE "SubMembers" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "MemberId" integer NOT NULL,
        "Name" character varying(256) NOT NULL,
        "MobileNo" character varying(32) NOT NULL,
        "Relation" character varying(64) NOT NULL,
        "IsActive" boolean NOT NULL,
        "Designation" character varying(256) NOT NULL,
        CONSTRAINT "PK_SubMembers" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SubMembers_Members_MemberId" FOREIGN KEY ("MemberId") REFERENCES "Members" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260411105454_InitialCreate') THEN
    CREATE INDEX "IX_SubMembers_MemberId" ON "SubMembers" ("MemberId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260411105454_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260411105454_InitialCreate', '8.0.11');
    END IF;
END $EF$;
COMMIT;

